### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by hecheng000** [yzqxy/Yolov8_obb_Prune_Track#21]
Traceback (most recent call last):
  File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 648, in <module>
    main(opt)
  File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 545, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 118, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc).to(device)  # create
  File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/models/yolo.py", line 180, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/models/yolo.py", line 332, in parse_model
    m = eval(m) if isinstance(m, str) else m  # eval strings
  File "<string>", line 1, in <module>
NameError: name 'Detect' is not defined

**Comment by yzqxy** [comment]
> Traceback (most recent call last): File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 648, in main(opt) File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 545, in main train(opt.hyp, opt, device, callbacks) File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 118, in train model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc).to(device) # create File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/models/yolo.py", line 180, in **init** self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch]) # model, savelist File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/models/yolo.py", line 332, in parse_model m = eval(m) if isinstance(m, str) else m # eval strings File "", line 1, in NameError: name 'Detect' is not defined

看看你的yaml文件，head输出头得是Detect_v8，不能是Detect

**Comment by hecheng000** [comment]
好的 谢谢


















在 2023-10-26 14:44:09，"morning tea" ***@***.***> 写道：

Traceback (most recent call last): File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 648, in main(opt) File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 545, in main train(opt.hyp, opt, device, callbacks) File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/train.py", line 118, in train model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc).to(device) # create File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/models/yolo.py", line 180, in init self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch]) # model, savelist File "/home/hc/下载/yolo/Yolov8_obb_Prune_Track-main/models/yolo.py", line 332, in parse_model m = eval(m) if isinstance(m, str) else m # eval strings File "", line 1, in NameError: name 'Detect' is not defined

看看你的yaml文件，head输出头得是Detect_v8，不能是Detect
