### ISSUE TITLE
关于conf-thres的设置问题，为什么只能大于0.3？

### ISSUE THREAD

**Issue by shangshan2023** [yzqxy/Yolov8_obb_Prune_Track#33]
我把nms_obb函数里的定义的置信度和iou阈值删除掉之后，发现只有conf-thres的值大于等于0.3的时候代码才能运行，否则就会报错
图片一直传不上来，报错信息是这样的：
(base) root@autodl-container-b8cd119e52-de25f846:~/autodl-tmp/Yolov8_obb_Prune_Track-main# python valalign.py 
valalign: data=data/dior.yaml, weights=runs/train/yolov8m_flipud2/weights/best.pt, batch_size=8, imgsz=800, conf_thres=0.2, iou_thres=0.1, task=test, device=0, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
WARNING: In oriented detection, confidence threshold 0.2 >> 0.01 will produce invalid mAP values.
YOLOv5 🚀 2023-11-6 torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11020MiB)

test: Scanning '/root/autodl-tmp/datasets/dior/test' images and labels...11738 found, 0 missing, 55 empty, 0 corrupted: 100%|██████████████████████████████████████████| 11738/11738 [00:01<00:00, 10428.35it/s]
test: New cache created: /root/autodl-tmp/datasets/dior/test.cache
               Class     Images     Labels          P          R  OBBmAP@.5      OBBmAP@.5:.95:   1%|▏         | 19/1468 [00:04<05:19,  4.54it/s]                                                               
Traceback (most recent call last):
  File "valalign.py", line 418, in <module>
    main(opt)
  File "valalign.py", line 391, in main
    run(**vars(opt))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "valalign.py", line 244, in run
    confusion_matrix.process_batch(pred, labels)
  File "/root/autodl-tmp/Yolov8_obb_Prune_Track-main/utils/metrics.py", line 142, in process_batch
    iou = box_iou_rotated(labels[:, 1:],detections[:, :5])
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/ops/box_iou_rotated.py", line 152, in box_iou_rotated
    ext_module.box_iou_rotated(
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by shangshan2023** [comment]
![Uploading DFE~J_W(J8M4YCS}B)S`RON.png…]()

**Comment by shangshan2023** [comment]
![Uploading XV(7OI~5@Y~J9Q]QUJO73%L.png…]()

**Comment by shangshan2023** [comment]
1

**Comment by yzqxy** [comment]
你这个出错的问题和conf-thres没关系吧，不改之前能跑通么

**Comment by shangshan2023** [comment]
不改之前能跑通，一改这个参数就报错

**Comment by yzqxy** [comment]
> 不改之前能跑通，一改这个参数就报错

可能传参的时候有bug吧，有空我再实验一下，你自己可以先在出错的地方debug看看

**Comment by shangshan2023** [comment]
好，谢谢
