### ISSUE TITLE
'Model' object has no attribute 'module'. Did you mean: 'modules'?

### ISSUE THREAD

**Issue by Amberonetwo** [yzqxy/Yolov8_obb_Prune_Track#37]
作者大大求问这个是什么的问题，困扰很久了
Traceback (most recent call last):
  File "/content/drive/MyDrive/Yolov8_obb_Prune_Track-latest/train.py", line 672, in <module>
    main(opt)
  File "/content/drive/MyDrive/Yolov8_obb_Prune_Track-latest/train.py", line 569, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/drive/MyDrive/Yolov8_obb_Prune_Track-latest/train.py", line 275, in train
    compute_loss = v8PoseLoss(model)  # init loss class
  File "/content/drive/MyDrive/Yolov8_obb_Prune_Track-latest/utils/loss.py", line 186, in __init__
    self.kpt_shape = model.module.model[-1].kpt_shape
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'module'. Did you mean: 'modules'?

**Comment by duvnv2** [comment]
i also want to know

**Comment by Amberonetwo** [comment]
找到Yolov8_obb_Prune_Track/utils/loss.py路径下class v8PoseLoss类
将self.kpt_shape = model.module.model[-1].kpt_shape
改为self.kpt_shape = model.model[-1].kpt_shape大概在186行，问题解决
